// InkFrame Brush Engine V2 — generated release asset policy
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');
const temp = mkdtempSync(resolve(tmpdir(), 'inkframe-v2-release-'));
const generated = resolve(temp, 'index.html');

try {
  execFileSync(process.execPath, [
    resolve(root, 'tools/inject-brush-v2-index.mjs'),
    resolve(root, 'web/index.html'),
    generated,
    '--variant=release',
    '--diagnostics=false',
    '--default-engine=v2',
  ], { cwd:root, stdio:'pipe' });

  const html = readFileSync(generated, 'utf8');
  const compareSource=readFileSync(resolve(root,'web/brush-engine-v2/preview-compare.js'),'utf8');
  const radialSource=readFileSync(resolve(root,'web/radial-timeline.js'),'utf8');
  const timingSource=readFileSync(resolve(root,'web/radial-timing-editor.js'),'utf8');
  const patternsSource=readFileSync(resolve(root,'web/radial-timing-patterns.js'),'utf8');
  const recipesSource=readFileSync(resolve(root,'web/radial-timing-recipes.js'),'utf8');
  const variationsSource=readFileSync(resolve(root,'web/radial-timing-variations.js'),'utf8');
  const morphSource=readFileSync(resolve(root,'web/radial-timing-morph.js'),'utf8');
  const phrasesSource=readFileSync(resolve(root,'web/radial-timing-phrases.js'),'utf8');
  const phraseLibrarySource=readFileSync(resolve(root,'web/radial-timing-phrase-library.js'),'utf8');
  const scoreSource=readFileSync(resolve(root,'web/radial-timing-score.js'),'utf8');
  assert.ok(html.includes('INKFRAME_BRUSH_V2_RUNTIME'));
  assert.ok(html.includes('"variant":"release"'));
  assert.ok(html.includes('"diagnostics":false'));
  assert.ok(html.includes('"traceTools":false'));
  assert.ok(html.includes('"defaultBrushEngine":"v2"'));
  assert.ok(html.includes('<script src="canvas-shape.js"></script>'),'release index must load Circular Canvas');
  assert.ok(existsSync(resolve(root,'web/canvas-shape.js')),'missing Circular Canvas runtime');
  assert.ok(html.includes('InkFrameCanvasShapeEnvironment'),'release index must expose the per-project shape bridge');
  assert.ok(html.includes('InkFrameCanvasShape.acceptsPointerDown'),'release index must reject circle-corner starts');
  assert.ok(html.includes('InkFrameCanvasShape.boundaryEvent'),'release index must finish strokes at the circle rim');
  assert.ok(html.includes('InkFrameCanvasShape.maskComposite'),'release index must mask frame composites');
  assert.ok(html.includes("canvasShape:P.canvasShape==='circle'?'circle':'square'"),'release archives must preserve canvas shape');
  assert.ok(html.includes('<script src="radial-timeline.js"></script>'),'release index must load Radial Timeline');
  assert.ok(existsSync(resolve(root,'web/radial-timeline.js')),'missing Radial Timeline runtime');
  assert.ok(html.includes('<script src="radial-timing-editor.js"></script>'),'release index must load Radial Timing Editor');
  assert.ok(existsSync(resolve(root,'web/radial-timing-editor.js')),'missing Radial Timing Editor runtime');
  assert.ok(html.includes('<script src="radial-timing-patterns.js"></script>'),'release index must load Radial Timing Patterns');
  assert.ok(existsSync(resolve(root,'web/radial-timing-patterns.js')),'missing Radial Timing Patterns runtime');
  assert.ok(html.includes('<script src="radial-timing-recipes.js"></script>'),'release index must load Radial Timing Recipes');
  assert.ok(existsSync(resolve(root,'web/radial-timing-recipes.js')),'missing Radial Timing Recipes runtime');
  assert.ok(html.includes('<script src="radial-timing-variations.js"></script>'),'release index must load Radial Timing Variations');
  assert.ok(existsSync(resolve(root,'web/radial-timing-variations.js')),'missing Radial Timing Variations runtime');
  assert.ok(html.includes('<script src="radial-timing-morph.js"></script>'),'release index must load Radial Timing Morph');
  assert.ok(existsSync(resolve(root,'web/radial-timing-morph.js')),'missing Radial Timing Morph runtime');
  assert.ok(html.includes('<script src="radial-timing-phrases.js"></script>'),'release index must load Timing Phrase Composer');
  assert.ok(existsSync(resolve(root,'web/radial-timing-phrases.js')),'missing Timing Phrase Composer runtime');
  assert.ok(html.includes('<script src="radial-timing-phrase-library.js"></script>'),'release index must load Timing Phrase Library');
  assert.ok(existsSync(resolve(root,'web/radial-timing-phrase-library.js')),'missing Timing Phrase Library runtime');
  assert.ok(html.includes('<script src="radial-timing-score.js"></script>'),'release index must load Timing Score Composer');
  assert.ok(existsSync(resolve(root,'web/radial-timing-score.js')),'missing Timing Score Composer runtime');
  assert.ok(html.indexOf('radial-timeline.js')<html.indexOf('radial-timing-editor.js'),'Radial Timing Editor must load after Radial Timeline');
  assert.ok(html.indexOf('radial-timing-editor.js')<html.indexOf('radial-timing-patterns.js'),'Radial Timing Patterns must load after the direct editor');
  assert.ok(html.indexOf('radial-timing-patterns.js')<html.indexOf('radial-timing-recipes.js'),'Radial Timing Recipes must load after built-in rhythms');
  assert.ok(html.indexOf('radial-timing-recipes.js')<html.indexOf('radial-timing-variations.js'),'Radial Timing Variations must load after reusable recipes');
  assert.ok(html.indexOf('radial-timing-variations.js')<html.indexOf('radial-timing-morph.js'),'Radial Timing Morph must load after deterministic variations');
  assert.ok(html.indexOf('radial-timing-morph.js')<html.indexOf('radial-timing-phrases.js'),'Timing Phrase Composer must load after Morph');
  assert.ok(html.indexOf('radial-timing-phrases.js')<html.indexOf('radial-timing-phrase-library.js'),'Timing Phrase Library must load after Phrase Composer');
  assert.ok(html.indexOf('radial-timing-phrase-library.js')<html.indexOf('radial-timing-score.js'),'Timing Score Composer must load after Phrase Library');
  assert.ok(existsSync(resolve(root,'tools/inject-radial-timeline.mjs')),'missing Radial Timeline injector');
  assert.ok(html.includes('InkFrameRadialTimeline.render(board'),'release index must delegate frame-board rendering');
  assert.ok(html.includes('InkFrameRadialTimeline.refreshThumbnail(cur,thumb)'),'release index must refresh orbital thumbnails');
  assert.ok(html.includes('InkFrameRadialTimeline.syncPlayback({'),'release index must synchronize the orbital playhead from the established rail');
  assert.ok(html.includes('project:projects[pi]'),'release bridge must isolate navigation view by project');
  assert.ok(html.includes('playing,fps,loopOn,loopIn,loopOut'),'release bridge must expose established playback state');
  assert.ok(html.includes('playbackFraction:frameCenterFrac(cur)'),'release bridge must seed hold-aware orbital playback position');
  assert.ok(html.includes('canNavigate:()=>'),'release bridge must block navigation during active strokes');
  assert.ok(html.includes('canEditTiming:()=>'),'release bridge must block timing edits during active strokes');
  assert.ok(html.includes('seek:i=>'),'release bridge must expose bounded frame seeking');
  assert.ok(html.includes('seekFraction:f=>'),'release bridge must delegate orbital scrubbing to hold-weighted rail seeking');
  assert.ok(html.includes('togglePlayback:()=>'),'release bridge must delegate play/pause to the established animation engine');
  assert.ok(html.includes('setHold:(i,v)=>'),'release bridge must delegate radial hold edits to the established hold array');
  assert.ok(html.includes('setHolds:entries=>'),'release bridge must expose one batched hold transaction for exposure rhythms');
  assert.ok(html.includes('setLoopRange:(a,b)=>'),'release bridge must delegate loop handles to established loop bounds');
  assert.ok(html.includes('toggleLoop:()=>'),'release bridge must delegate loop enablement to the existing loop control');
  assert.ok(html.includes("AUTOSAVE.schedule)AUTOSAVE.schedule()"),'timing mutations must schedule existing project recovery');
  assert.ok(html.includes('fraction:activeFraction,current:cur,playing,loopOn,loopIn,loopOut,fps'),'release rail must publish continuous playback progress');
  assert.ok(radialSource.includes('inkframe-radial-hit'),'Radial Timeline must expose orbit-only drag targets');
  assert.ok(radialSource.includes('inkframe-radial-playhead'),'Radial Timeline must expose the continuous orbital playhead');
  assert.ok(radialSource.includes('inkframe-radial-loop'),'Radial Timeline must expose loop-range arcs');
  assert.ok(radialSource.includes('inkframe-radial-scrub'),'Radial Timeline must expose explicit scrub mode');
  assert.ok(radialSource.includes('function timingMap'),'Radial Timeline must derive progress from frame holds');
  assert.ok(radialSource.includes('function playbackPoint'),'Radial Timeline must project hold-weighted time onto its orbit');
  assert.ok(radialSource.includes('function loopSegments'),'Radial Timeline must split loop ranges across concentric rings');
  assert.ok(radialSource.includes('function syncPlayback'),'Radial Timeline must accept the rail as playback source of truth');
  assert.ok(radialSource.includes('focusCurrent'),'Radial Timeline must expose current-frame centering');
  assert.ok(radialSource.includes('toggleRingFocus'),'Radial Timeline must expose ring focus');
  assert.ok(radialSource.includes('toggleScrubMode'),'Radial Timeline must expose presentation-only scrubbing');
  assert.ok(radialSource.includes("event.key==='ArrowRight'"),'Radial Timeline must expose keyboard stepping');
  assert.ok(radialSource.includes("event.key===' '"),'Radial Timeline must expose keyboard play/pause');
  assert.ok(radialSource.includes('aria-activedescendant'),'Radial Timeline must expose active-frame accessibility state');
  assert.ok(radialSource.includes('const projectViews=new WeakMap()'),'Radial Timeline view state must remain non-persistent and per-project');
  assert.ok(radialSource.includes('projectCanvasWrites:0'),'Radial Timeline must declare project-canvas isolation');
  assert.ok(radialSource.includes('undoWrites:0'),'Radial Timeline must declare artwork-undo isolation');
  assert.ok(timingSource.includes('inkframe-hold-arc'),'Radial Timing Editor must visualize every established frame hold');
  assert.ok(timingSource.includes('inkframe-radial-timing-toggle'),'Radial Timing Editor must expose explicit timing mode');
  assert.ok(timingSource.includes('inkframe-timing-loop-handle'),'Radial Timing Editor must expose direct loop in/out handles');
  assert.ok(timingSource.includes('function holdFromRadialDrag'),'Radial Timing Editor must quantize outward/inward hold gestures');
  assert.ok(timingSource.includes('function holdArcGeometry'),'Radial Timing Editor must derive deterministic hold arcs');
  assert.ok(timingSource.includes('function clampLoopRange'),'Radial Timing Editor must keep loop bounds ordered and bounded');
  assert.ok(timingSource.includes('const projectViews=new WeakMap()'),'Radial timing mode must remain memory-only and isolated by project');
  assert.ok(timingSource.includes('canEditTiming'),'Radial Timing Editor must honor active-stroke guards');
  assert.ok(timingSource.includes('projectCanvasWrites:0'),'Radial Timing Editor must declare project-canvas isolation');
  assert.ok(timingSource.includes('artworkUndoWrites:0'),'Radial Timing Editor must declare artwork-undo isolation');
  assert.ok(timingSource.includes('timelineTimingWrites:true'),'Radial Timing Editor must explicitly declare its bounded timeline mutation scope');
  assert.ok(patternsSource.includes("freezePattern('ease-in'"),'Radial Timing Patterns must ship deterministic built-in rhythms');
  assert.ok(patternsSource.includes('function resolveTargetIndices'),'Radial Timing Patterns must resolve selection, loop, and full-timeline scopes');
  assert.ok(patternsSource.includes("kind:'selection'"),'selected frames must take scope priority');
  assert.ok(patternsSource.includes("kind:'loop'"),'active loop ranges must be available as rhythm scope');
  assert.ok(patternsSource.includes('inkframe-rhythm-preview-svg'),'Radial Timing Patterns must expose non-destructive preview arcs');
  assert.ok(patternsSource.includes('inkframe-rhythm-undo'),'Radial Timing Patterns must expose timing-only undo');
  assert.ok(patternsSource.includes('inkframe-rhythm-redo'),'Radial Timing Patterns must expose timing-only redo');
  assert.ok(patternsSource.includes('lastEnvironment.setHolds(entries)'),'Radial Timing Patterns must use the batched hold bridge');
  assert.ok(patternsSource.includes('function commitAssignments'),'Radial Timing Patterns must expose one shared timing-history transaction');
  assert.ok(patternsSource.includes('const projectViews=new WeakMap(),projectHistories=new WeakMap()'),'rhythm view and history must remain memory-only per project');
  assert.ok(patternsSource.includes('canEditTiming'),'Radial Timing Patterns must honor active-stroke guards');
  assert.ok(patternsSource.includes('projectCanvasWrites:0'),'Radial Timing Patterns must declare project-canvas isolation');
  assert.ok(patternsSource.includes('artworkUndoWrites:0'),'Radial Timing Patterns must declare artwork-undo isolation');
  assert.ok(patternsSource.includes('timelineTimingWrites:true'),'Radial Timing Patterns must declare bounded timing writes');
  assert.ok(patternsSource.includes('projectSchemaWrites:0'),'Radial Timing Patterns must declare zero schema writes');
  assert.ok(recipesSource.includes("const STORAGE_KEY='inkframe.radialTiming.recipes.v1'"),'Timing Recipes must use a versioned device-library key');
  assert.ok(recipesSource.includes('const SCHEMA=1,MAX_RECIPES=24'),'Timing Recipes must bound and version the device library');
  assert.ok(recipesSource.includes('function minimalPeriod'),'Timing Recipes must reduce captured repetitions to their smallest exact core');
  assert.ok(recipesSource.includes('function transformValues'),'Timing Recipes must support phase and reversal transforms');
  assert.ok(recipesSource.includes('function createRecipeStore'),'Timing Recipes must expose a sanitized persistent library');
  assert.ok(recipesSource.includes('inkframe-recipe-preview-svg'),'Timing Recipes must expose non-destructive transformed preview arcs');
  assert.ok(recipesSource.includes('patterns.commitAssignments'),'Timing Recipes must share established timing-only Undo and Redo');
  assert.ok(recipesSource.includes('const projectViews=new WeakMap()'),'Timing Recipe controls must remain memory-only per project');
  assert.ok(recipesSource.includes('canEditTiming'),'Timing Recipes must honor active-stroke guards');
  assert.ok(recipesSource.includes('projectCanvasWrites:0'),'Timing Recipes must declare project-canvas isolation');
  assert.ok(recipesSource.includes('artworkUndoWrites:0'),'Timing Recipes must declare artwork-undo isolation');
  assert.ok(recipesSource.includes('projectSchemaWrites:0,deviceLibraryWrites:true'),'Timing Recipes must isolate device persistence from project schema');
  assert.ok(variationsSource.includes('const MAX_PHASE_VARIANTS=12'),'Timing Variations must visibly bound phase siblings');
  assert.ok(variationsSource.includes('function generateVariations'),'Timing Variations must deterministically derive sibling recipes');
  assert.ok(variationsSource.includes('function palindromeValues'),'Timing Variations must expose palindrome transforms');
  assert.ok(variationsSource.includes('function pulseValues'),'Timing Variations must expose pulse transforms');
  assert.ok(variationsSource.includes('function compressValues'),'Timing Variations must expose compressed timing');
  assert.ok(variationsSource.includes('function expandValues'),'Timing Variations must expose expanded timing');
  assert.ok(variationsSource.includes('inkframe-variation-preview-svg'),'Timing Variations must expose non-destructive preview arcs');
  assert.ok(variationsSource.includes('patterns.commitAssignments'),'Timing Variations must share timing-only Undo and Redo');
  assert.ok(variationsSource.includes('recipes.store.save'),'Timing Variations must save siblings through the established device library');
  assert.ok(variationsSource.includes('const projectViews=new WeakMap()'),'Timing Variation controls must remain memory-only per project');
  assert.ok(variationsSource.includes('canEditTiming'),'Timing Variations must honor active-stroke guards');
  assert.ok(variationsSource.includes('projectCanvasWrites:0'),'Timing Variations must declare project-canvas isolation');
  assert.ok(variationsSource.includes('artworkUndoWrites:0'),'Timing Variations must declare artwork-undo isolation');
  assert.ok(variationsSource.includes('projectSchemaWrites:0,deviceLibraryWrites:true,randomWrites:0'),'Timing Variations must declare deterministic isolated persistence');
  assert.ok(morphSource.includes('const MAX_ALIGNED_VALUES=120'),'Timing Morph must bound cyclic alignment');
  assert.ok(morphSource.includes('function greatestCommonDivisor'),'Timing Morph must expose deterministic period arithmetic');
  assert.ok(morphSource.includes('function alignmentLength'),'Timing Morph must align source recipe periods');
  assert.ok(morphSource.includes('function blendValues'),'Timing Morph must interpolate normalized hold values');
  assert.ok(morphSource.includes('function blendName'),'Timing Morph must preserve source and mix provenance');
  assert.ok(morphSource.includes('inkframe-morph-preview-svg'),'Timing Morph must expose non-destructive preview arcs');
  assert.ok(morphSource.includes('patterns.commitAssignments'),'Timing Morph must share timing-only Undo and Redo');
  assert.ok(morphSource.includes('recipes.store.save'),'Timing Morph must save blends through the established device library');
  assert.ok(morphSource.includes('const projectViews=new WeakMap()'),'Timing Morph controls must remain memory-only per project');
  assert.ok(morphSource.includes('canEditTiming'),'Timing Morph must honor active-stroke guards');
  assert.ok(morphSource.includes('sourceRecipeWrites:0,randomWrites:0'),'Timing Morph must preserve source recipes and remain deterministic');
  assert.ok(morphSource.includes('projectCanvasWrites:0'),'Timing Morph must declare project-canvas isolation');
  assert.ok(morphSource.includes('artworkUndoWrites:0'),'Timing Morph must declare artwork-undo isolation');
  assert.ok(morphSource.includes('projectSchemaWrites:0,deviceLibraryWrites:true'),'Timing Morph must isolate device persistence from project schema');
  assert.ok(phrasesSource.includes('const MAX_SEGMENTS=8,MAX_REPEAT=4,MAX_VALUES=120'),'Timing Phrase Composer must bound sections, repeats, and output values');
  assert.ok(phrasesSource.includes('function compileSegments'),'Timing Phrase Composer must deterministically compile ordered recipe segments');
  assert.ok(phrasesSource.includes('function loadArrangement'),'Timing Phrase Composer must expose an explicit editable arrangement load boundary');
  assert.ok(phrasesSource.includes('inkframe-phrase-preview-svg'),'Timing Phrase Composer must expose non-destructive preview arcs');
  assert.ok(phrasesSource.includes('patterns.commitAssignments'),'Timing Phrase Composer must share timing-only Undo and Redo');
  assert.ok(phrasesSource.includes('recipes.store.save'),'Timing Phrase Composer must save compiled phrases through the established recipe library');
  assert.ok(phrasesSource.includes('const projectViews=new WeakMap()'),'Timing Phrase Composer state must remain memory-only per project');
  assert.ok(phrasesSource.includes('canEditTiming'),'Timing Phrase Composer must honor active-stroke guards');
  assert.ok(phrasesSource.includes('projectSchemaWrites:0,deviceLibraryWrites:true,sourceRecipeWrites:0,randomWrites:0'),'Timing Phrase Composer must isolate deterministic device writes');
  assert.ok(phraseLibrarySource.includes("const STORAGE_KEY='inkframe.radialTiming.phraseLibrary.v1'"),'Timing Phrase Library must use a versioned device-library key');
  assert.ok(phraseLibrarySource.includes('const SCHEMA=1,MAX_PHRASES=16,MAX_SEGMENTS=8'),'Timing Phrase Library must visibly bound and version editable arrangements');
  assert.ok(phraseLibrarySource.includes('function resolveRecord'),'Timing Phrase Library must report changed and missing source provenance');
  assert.ok(phraseLibrarySource.includes('function createPhraseLibraryStore'),'Timing Phrase Library must expose a sanitized persistent store');
  assert.ok(phraseLibrarySource.includes('phrases.loadArrangement'),'Timing Phrase Library must restore editable composer structure explicitly');
  assert.ok(phraseLibrarySource.includes('const projectViews=new WeakMap()'),'Timing Phrase Library selection must remain memory-only per project');
  assert.ok(phraseLibrarySource.includes('canEditTiming'),'Timing Phrase Library must honor active-stroke guards');
  assert.ok(phraseLibrarySource.includes('timelineTimingWrites:0,projectSchemaWrites:0,deviceLibraryWrites:true,sourceRecipeWrites:0,randomWrites:0,transientPhraseWrites:true'),'Timing Phrase Library must isolate structure persistence from timing and project schema');
  assert.ok(scoreSource.includes('const MAX_SECTIONS=8,MAX_REPEAT=4,MAX_VALUES=120'),'Timing Score Composer must bound sections, repeats, and output values');
  assert.ok(scoreSource.includes('function resolveArrangement'),'Timing Score Composer must resolve current phrase and recipe provenance');
  assert.ok(scoreSource.includes('function createScore'),'Timing Score Composer must deterministically compile ordered phrase sections');
  assert.ok(scoreSource.includes('inkframe-score-preview-svg'),'Timing Score Composer must expose non-destructive preview arcs');
  assert.ok(scoreSource.includes('patterns.commitAssignments'),'Timing Score Composer must share timing-only Undo and Redo');
  assert.ok(scoreSource.includes('recipes.store.save'),'Timing Score Composer must save compiled scores through the established recipe library');
  assert.ok(scoreSource.includes('const projectViews=new WeakMap()'),'Timing Score Composer state must remain memory-only per project');
  assert.ok(scoreSource.includes('canEditTiming'),'Timing Score Composer must honor active-stroke guards');
  assert.ok(scoreSource.includes('sourceArrangementWrites:0,sourceRecipeWrites:0,randomWrites:0'),'Timing Score Composer must preserve all sources and remain deterministic');
  assert.ok(scoreSource.includes('projectCanvasWrites:0'),'Timing Score Composer must declare project-canvas isolation');
  assert.ok(scoreSource.includes('artworkUndoWrites:0'),'Timing Score Composer must declare artwork-undo isolation');
  assert.ok(scoreSource.includes('projectSchemaWrites:0,deviceLibraryWrites:true'),'Timing Score Composer must isolate device persistence from project schema');
  for(const script of [
    'stabilizer.js','ghost-trail.js','runtime.js','ghost-runtime.js',
    'stabilizer-ui.js','ghost-ui.js','user-presets.js','lab-ui.js','preset-ui.js','preview-compare.js','preview-pad.js',
  ]){
    assert.ok(html.includes(`<script src="brush-engine-v2/${script}"></script>`),`missing release script ${script}`);
    assert.ok(existsSync(resolve(root,`web/brush-engine-v2/${script}`)),`missing runtime file ${script}`);
  }
  for(const asset of ['preview-replay.js','brush-coach.js','coach-session.js','calibration-report.js','profile-recovery.js','profile-recovery-observer.js','profile-identities.js','identity-mixer.js','brush-match.js','brush-signature.js']){
    assert.ok(existsSync(resolve(root,`web/brush-engine-v2/${asset}`)),`missing dynamic asset ${asset}`);
  }
  assert.ok(compareSource.includes("script.src='brush-engine-v2/preview-replay.js'"),'comparison runtime must load reference replay');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/brush-coach.js'"),'comparison runtime must load Brush Coach');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/coach-session.js'"),'comparison runtime must load Coach Session');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/calibration-report.js'"),'comparison runtime must load Calibration Report');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/profile-recovery.js'"),'comparison runtime must load Profile Recovery');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/profile-recovery-observer.js'"),'comparison runtime must load Profile Recovery Observer');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/profile-identities.js'"),'comparison runtime must load Creative Brush Identities');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/identity-mixer.js'"),'comparison runtime must load Identity Mixer');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/brush-match.js'"),'comparison runtime must load Brush Match');
  assert.ok(compareSource.includes("script.src='brush-engine-v2/brush-signature.js'"),'comparison runtime must load Brush Signature');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadBrushCoach,0)"),'Brush Coach must be scheduled from the reference replay load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadCoachSession,0)"),'Coach Session must be scheduled from the Brush Coach load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadCalibrationReport,0)"),'Calibration Report must be scheduled from the Coach Session load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadProfileRecovery,0)"),'Profile Recovery must be scheduled from the Calibration Report load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadProfileRecoveryObserver,0)"),'Profile Recovery Observer must be scheduled from the recovery load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadProfileIdentities,0)"),'Creative Identities must be scheduled from the observer load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadIdentityMixer,0)"),'Identity Mixer must be scheduled from the identity load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadBrushMatch,0)"),'Brush Match must be scheduled from the mixer load event');
  assert.ok(compareSource.includes("script.addEventListener('load',()=>root.setTimeout(loadBrushSignature,0)"),'Brush Signature must be scheduled from the Brush Match load event');
  assert.ok(compareSource.includes('script[data-inkframe-coach-session]'),'Coach Session loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-calibration-report]'),'Calibration Report loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-profile-recovery]'),'Profile Recovery loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-profile-recovery-observer]'),'Profile Recovery Observer loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-profile-identities]'),'Creative Identity loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-identity-mixer]'),'Identity Mixer loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-brush-match]'),'Brush Match loader must suppress duplicates');
  assert.ok(compareSource.includes('script[data-inkframe-brush-signature]'),'Brush Signature loader must suppress duplicates');
  assert.equal(html.includes('<script src="brush-engine-v2/native.js"></script>'), false);
  assert.ok(html.indexOf('brush-engine-v2/stabilizer.js') < html.indexOf('brush-engine-v2/filters.js'));
  assert.ok(html.indexOf('brush-engine-v2/rasterizer.js') < html.indexOf('brush-engine-v2/ghost-trail.js'));
  assert.ok(html.indexOf('brush-engine-v2/trace.js') < html.indexOf('brush-engine-v2/runtime.js'));
  assert.ok(html.indexOf('brush-engine-v2/tuning.js') < html.indexOf('brush-engine-v2/user-presets.js'));
  assert.ok(html.indexOf('brush-engine-v2/user-presets.js') < html.indexOf('brush-engine-v2/adapter.js'));
  assert.ok(html.indexOf('brush-engine-v2/runtime.js') < html.indexOf('brush-engine-v2/adapter.js'));
  assert.ok(html.indexOf('brush-engine-v2/session.js') < html.indexOf('brush-engine-v2/ghost-runtime.js'));
  assert.ok(html.indexOf('brush-engine-v2/ghost-runtime.js') < html.indexOf('brush-engine-v2/input.js'));
  assert.ok(html.indexOf('brush-engine-v2/ghost-ui.js') < html.indexOf('brush-engine-v2/lab-ui.js'));
  assert.ok(html.indexOf('brush-engine-v2/lab-ui.js') < html.indexOf('brush-engine-v2/preset-ui.js'));
  assert.ok(html.indexOf('brush-engine-v2/preset-ui.js') < html.indexOf('brush-engine-v2/preview-compare.js'));
  assert.ok(html.indexOf('brush-engine-v2/preview-compare.js') < html.indexOf('brush-engine-v2/preview-pad.js'));
  assert.ok(html.includes('InkFrameBrushV2InputBridge.begin'));
  assert.ok(html.includes('coordinateTransform:inputTransform'));

  console.log('✅ generated Brush V2 production recovery, Circular Canvas, radial timing, recipes, variations, morphs, phrases, phrase library, and score policy passed');
} finally {
  rmSync(temp, { recursive:true, force:true });
}

await import('./canvas-shape.test.mjs');
await import('./canvas-shape-autosave.test.mjs');
await import('./canvas-shape-boot.test.mjs');
await import('./radial-timeline.test.mjs');
await import('./radial-timeline-boot.test.mjs');
await import('./radial-timing-editor.test.mjs');
await import('./radial-timing-editor-boot.test.mjs');
await import('./radial-timing-patterns.test.mjs');
await import('./radial-timing-patterns-boot.test.mjs');
await import('./radial-timing-recipes.test.mjs');
await import('./radial-timing-recipes-boot.test.mjs');
await import('./radial-timing-variations.test.mjs');
await import('./radial-timing-variations-boot.test.mjs');
await import('./radial-timing-morph.test.mjs');
await import('./radial-timing-morph-boot.test.mjs');
await import('./android-branding.test.mjs');
