// InkFrame Brush Engine V2 — deterministic identity matching from reference strokes
'use strict';
(function(root){
  const ns=root.InkFrameBrushV2||(root.InkFrameBrushV2={});
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
  const round=(value,places=3)=>{const scale=10**places;return Math.round((Number(value)||0)*scale)/scale;};
  const RANGES=Object.freeze({stabilizerStrength:200,cornerStrength:100,ghostIntensity:100,ghostDurationMs:1120,ghostWidthPercent:200,positionTimeConstantMs:39.5,pressureTimeConstantMs:49.5,spacingScale:1.4,minimumJump:196,speedLimitPxPerMs:19});
  const WEIGHTS=Object.freeze({stabilizerStrength:2.2,cornerStrength:1.7,ghostIntensity:.8,ghostDurationMs:.45,ghostWidthPercent:.4,positionTimeConstantMs:1.25,pressureTimeConstantMs:1.1,spacingScale:.85,minimumJump:.65,speedLimitPxPerMs:.8});
  function tuningDistance(targetValue,candidateValue){
    const target=ns.normalizeTuning?ns.normalizeTuning(targetValue||{}):targetValue||{},candidate=ns.normalizeTuning?ns.normalizeTuning(candidateValue||{}):candidateValue||{};let total=0,weight=0;
    for(const key of Object.keys(RANGES)){const w=WEIGHTS[key]||1;total+=Math.abs((Number(target[key])||0)-(Number(candidate[key])||0))/RANGES[key]*w;weight+=w;}
    const ghostPenalty=target.ghostMode===candidate.ghostMode?0:((target.ghostMode==='off'||candidate.ghostMode==='off')?.12:.2);return round(clamp(total/Math.max(1,weight)+ghostPenalty,0,1),5);
  }
  function rankBrushIdentities(target){
    const identities=Array.from(ns.listBrushIdentities?ns.listBrushIdentities():[]);return Object.freeze(identities.map(identity=>{const distance=tuningDistance(target,identity.tuning);return Object.freeze({identity,distance,score:round(1-distance,4)});}).sort((a,b)=>a.distance-b.distance||a.identity.id.localeCompare(b.identity.id)));
  }
  function matchTuningToIdentities(targetValue,options){
    const config=options||{},target=ns.normalizeTuning?ns.normalizeTuning(targetValue||{}):targetValue||{},identities=Array.from(ns.listBrushIdentities?ns.listBrushIdentities():[]),ranking=rankBrushIdentities(target);
    if(identities.length<2||!ns.mixBrushIdentities)return Object.freeze({valid:false,label:'No match',reason:'Identity Mixer unavailable',target});
    let best=null;
    for(let i=0;i<identities.length;i++)for(let j=i+1;j<identities.length;j++)for(let percent=0;percent<=100;percent++){
      const mix=ns.mixBrushIdentities(identities[i],identities[j],percent),distance=tuningDistance(target,mix.tuning),key=`${identities[i].id}|${identities[j].id}|${String(percent).padStart(3,'0')}`;
      if(!best||distance<best.distance-1e-8||(Math.abs(distance-best.distance)<=1e-8&&key<best.key))best={mix,distance,key};
    }
    const score=round(1-best.distance,4),baseConfidence=clamp(Number(config.confidence)||.75,.5,.99),confidence=round(clamp(baseConfidence*(.72+score*.28),.5,.97),2);
    return Object.freeze({valid:true,id:String(config.id||'identity-match:recommended'),kind:String(config.kind||'identity-match'),label:`Matched · ${best.mix.presetName.replace(/^Mix /,'')}`,confidence,score,distance:best.distance,target,mix:best.mix,tuning:best.mix.tuning,ranking:Object.freeze(ranking.slice(0,3))});
  }
  function matchBrushIdentities(analysis,currentValue){
    if(!analysis||!analysis.valid)return Object.freeze({valid:false,label:'No match',reason:analysis&&analysis.reason||'Draw a longer reference stroke',analysis});
    const recommendation=ns.recommendationFromAnalysis?ns.recommendationFromAnalysis(analysis,currentValue||{}):null;if(!recommendation||!recommendation.valid)return Object.freeze({valid:false,label:'No match',reason:'Brush Coach target unavailable',analysis});
    const core=matchTuningToIdentities(recommendation.tuning,{id:'brush-match:recommended',kind:'brush-match',confidence:recommendation.confidence});if(!core.valid)return Object.freeze(Object.assign({},core,{analysis,recommendation}));
    return Object.freeze({valid:true,id:core.id,kind:core.kind,label:core.label,confidence:core.confidence,score:core.score,distance:core.distance,analysis,recommendation,mix:core.mix,tuning:core.tuning,ranking:core.ranking,reasons:Object.freeze([`Reference intent: ${analysis.intent}.`,`Closest generated blend: ${core.mix.name}.`,`Match score: ${Math.round(core.score*100)}%.`])});
  }
  function brushMatchChips(match){if(!match||!match.valid)return Object.freeze([]);return Object.freeze([`${Math.round(match.confidence*100)}% confidence`,`${Math.round(match.score*100)}% tuning match`,`${Math.round(100-match.mix.percent)}% ${match.mix.a.name}`,`${Math.round(match.mix.percent)}% ${match.mix.b.name}`]);}

  function install(){
    const coach=root.InkFrameBrushCoach,mixer=root.InkFrameBrushIdentityMixer,preview=root.InkFrameBrushV2PreviewPad,replay=root.InkFrameBrushV2ReferenceReplay,recovery=root.InkFrameBrushProfileRecovery,adapter=root.InkFrameBrushV2Adapter,presetUi=root.InkFrameBrushV2PresetUI,store=presetUi&&presetUi.store;
    if(!root.document||!coach||!coach.installed||!mixer||!mixer.installed||!mixer.details||!preview||!preview.installed||!replay||!replay.recorder||!recovery||!adapter||!store)return false;
    if(root.InkFrameBrushMatch&&root.InkFrameBrushMatch.installed)return true;
    let match=null;
    const details=root.document.createElement('details');details.className='inkframe-v2-brush-match';details.innerHTML='<summary>Brush Match · Draw a reference</summary><div class="inkframe-v2-brush-match-body"><strong class="inkframe-v2-brush-match-name">Draw a reference stroke in Brush Preview</strong><p class="inkframe-v2-brush-match-description"></p><div class="inkframe-v2-brush-match-chips"></div><div class="inkframe-v2-brush-match-ranking"></div><div class="inkframe-v2-brush-match-actions"><button class="primary">Preview Match</button><button>Load in Mixer</button><button>Apply Match</button><button>Save + Pin</button><button>Apply + Lock</button></div></div>';
    const style=root.document.createElement('style');style.textContent='.inkframe-v2-brush-match{margin-top:9px;border-top:1px solid rgba(255,255,255,.1);padding-top:8px}.inkframe-v2-brush-match>summary{cursor:pointer;font:760 10px/1.2 system-ui}.inkframe-v2-brush-match-body{display:grid;gap:8px;padding-top:8px}.inkframe-v2-brush-match-name{font:760 11px/1.2 system-ui}.inkframe-v2-brush-match-description{margin:0;font:620 9px/1.4 system-ui;opacity:.72}.inkframe-v2-brush-match-chips{display:flex;flex-wrap:wrap;gap:5px}.inkframe-v2-brush-match-chips span,.inkframe-v2-brush-match-ranking span{border:1px solid rgba(255,255,255,.11);border-radius:999px;background:rgba(255,255,255,.05);padding:5px 7px;font:680 8px/1 system-ui}.inkframe-v2-brush-match-ranking{display:flex;flex-wrap:wrap;gap:5px}.inkframe-v2-brush-match-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.inkframe-v2-brush-match-actions button{min-height:40px;border:1px solid rgba(255,255,255,.14);border-radius:10px;background:rgba(255,255,255,.06);color:#fff;padding:7px 9px;font:700 9px/1.1 system-ui}.inkframe-v2-brush-match-actions button.primary{background:linear-gradient(145deg,#a6005c,#590051)}.inkframe-v2-brush-match-actions button:last-child{grid-column:1/3}';root.document.head.appendChild(style);mixer.details.insertAdjacentElement('afterend',details);
    const summary=details.querySelector(':scope>summary'),name=details.querySelector('.inkframe-v2-brush-match-name'),description=details.querySelector('.inkframe-v2-brush-match-description'),chips=details.querySelector('.inkframe-v2-brush-match-chips'),ranking=details.querySelector('.inkframe-v2-brush-match-ranking'),actions=Array.from(details.querySelectorAll('.inkframe-v2-brush-match-actions button'));
    function refresh(){const analysis=ns.analyzeReferenceStroke(replay.recorder.snapshot());match=matchBrushIdentities(analysis,adapter.currentTuning());const busy=!!(adapter.isActive&&adapter.isActive());actions.forEach(button=>button.disabled=!match.valid||busy);chips.replaceChildren();ranking.replaceChildren();if(!match.valid){summary.textContent='Brush Match · Draw a reference';name.textContent='Draw a reference stroke in Brush Preview';description.textContent=match.reason||'';return match;}summary.textContent=`Brush Match · ${Math.round(match.score*100)}%`;name.textContent=match.label;description.textContent=match.reasons.join(' ');chips.replaceChildren(...brushMatchChips(match).map(value=>{const node=root.document.createElement('span');node.textContent=value;return node;}));ranking.replaceChildren(...match.ranking.map((item,index)=>{const node=root.document.createElement('span');node.textContent=`#${index+1} ${item.identity.name} ${Math.round(item.score*100)}%`;return node;}));return match;}
    function previewMatch(){if(!match||!match.valid||adapter.isActive&&adapter.isActive())return false;const choice=preview.setTransientCompare&&preview.setTransientCompare(match.label,match.tuning);if(!choice)return false;replay.replay&&replay.replay();return true;}
    function loadInMixer(){if(!match||!match.valid||adapter.isActive&&adapter.isActive())return false;mixer.setA(match.mix.a.id);mixer.setB(match.mix.b.id);mixer.setPercent(match.mix.percent);mixer.details.open=true;mixer.details.scrollIntoView&&mixer.details.scrollIntoView({block:'nearest'});return true;}
    function applyMatch(){if(!match||!match.valid||adapter.isActive&&adapter.isActive())return false;const ok=adapter.setTuning(match.tuning);if(ok&&root.InkFrameBrushV2LabUI&&root.InkFrameBrushV2LabUI.updateSummaries)root.InkFrameBrushV2LabUI.updateSummaries();refresh();return !!ok;}
    function saveAndPin(){if(!match||!match.valid)return null;try{const preset=store.save(`Match ${Math.round(match.score*100)} · ${match.mix.a.name.split(/\s+/)[0]}/${match.mix.b.name.split(/\s+/)[0]}`.slice(0,32),match.tuning,true);presetUi.render&&presetUi.render();return preset||null;}catch(error){if(typeof root.alert==='function')root.alert(String(error&&error.message||error));return null;}}
    function applyAndLock(){if(!applyMatch())return false;recovery.lock();refresh();return true;}
    actions[0].addEventListener('click',previewMatch);actions[1].addEventListener('click',loadInMixer);actions[2].addEventListener('click',applyMatch);actions[3].addEventListener('click',saveAndPin);actions[4].addEventListener('click',applyAndLock);preview.card&&preview.card.addEventListener('pointerup',()=>root.setTimeout(refresh,0),true);preview.card&&preview.card.addEventListener('pointercancel',()=>root.setTimeout(refresh,0),true);root.setTimeout(refresh,0);
    root.InkFrameBrushMatch=Object.freeze({installed:true,details,refresh,current:()=>match,preview:previewMatch,loadInMixer,apply:applyMatch,saveAndPin,applyAndLock,render:refresh,projectCanvasWrites:0,undoWrites:0});return true;
  }
  const api={BRUSH_MATCH_RANGES:RANGES,BRUSH_MATCH_WEIGHTS:WEIGHTS,tuningDistance,rankBrushIdentities,matchTuningToIdentities,matchBrushIdentities,brushMatchChips,install};Object.assign(ns,api);root.InkFrameBrushMatch=api;if(root.document){const start=()=>{if(!install())root.setTimeout(start,16);};if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',start,{once:true});else start();}if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);